mixed-port: 7890
allow-lan: true
ipv6: true
mode: rule
log-level: silent
keep-alive-interval: 1800
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:12353
  ipv6: true
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.gstatic.com"
    - "connect.rom.miui.com"
    - "localhost.sec.qq.com"
    - "localhost.ptlogin2.qq.com"
    - "+.linksys.com"
    - "+.pool.ntp.org"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "lens.l.google.com"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - "xbox.*.*.microsoft.com"
    - "+.xboxlive.com"
    - "+.mcdn.bilivideo.cn"
    - "hiwifi.com"
    - "leike.cc"
    - "miwifi.com"
    - "my.router"
    - "peiluyou.com"
    - "phicomm.me"
    - "router.ctc"
    - "routerlogin.com"
    - "tendawifi.com"
    - "tplinkwifi.net"
    - "tplogin.cn"
    - "zte.home"
  nameserver:
    - "https://223.5.5.5/dns-query"
    - "https://1.12.12.12/dns-query"
  fallback:
    - "https://1.1.1.1/dns-query"
    - "https://8.8.8.8/dns-query"
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
  nameserver-policy:
    "geosite:cn,private":
      - "https://223.5.5.5/dns-query"
      - "https://1.12.12.12/dns-query"
    "geosite:geolocation-!cn":
      - "https://1.1.1.1/dns-query"
      - "https://8.8.8.8/dns-query"
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com