mixed-port: 7890
allow-lan: true
ipv6: true
mode: rule
log-level: silent
dns:
  enable: true
  listen: 0.0.0.0:12353
  ipv6: true
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.lan"
    - "+.gstatic.com"
    - "connect.rom.miui.com"
    - "localhost.sec.qq.com"
    - "localhost.ptlogin2.qq.com"
    - "+.linksys.com"
    - "+.pool.ntp.org"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "lens.l.google.com"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - "xbox.*.*.microsoft.com"
    - "+.xboxlive.com"
    - "+.mcdn.bilivideo.cn"
    - "hiwifi.com"
    - "leike.cc"
    - "miwifi.com"
    - "my.router"
    - "peiluyou.com"
    - "phicomm.me"
    - "router.ctc"
    - "routerlogin.com"
    - "tendawifi.com"
    - "tplinkwifi.net"
    - "tplogin.cn"
    - "zte.home"
  nameserver:
    - "https://223.5.5.5/dns-query"
    - "https://1.12.12.12/dns-query"
  fallback:
    - "https://1.1.1.1/dns-query"
    - "https://94.140.14.140/dns-query"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
# script:
#   engine: expr
#   shortcuts:
#     FKLoopback: resolve_process_name() == 'clash' and network == 'udp'